saveExact: true
nodeLinker: hoisted

overrides:
  '@solidjs/vite-plugin>babel-preset-solid': 2.0.0-rc.1
  '@codemirror/commands': 6.10.4
  '@codemirror/view': 6.43.8
  esbuild: 0.28.1
  'vite-node>vite': 7.3.5
  'vitest>vite': 7.3.5

allowBuilds:
  electron-winstaller: true
  esbuild: true
